version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-react-matching-app2
    ports:
      - "3000:3000"
    depends_on:
      - db



      #rails new rails_api --api --database=postgresql

      #docker-compose run api rails new . --force --no-deps -d mysql --api

#docker-compose run --no-deps web rails new rails_api --api . --force --database=postgresql
